### ISSUE TITLE
Alternate pins after breaking metal pads

### ISSUE THREAD

**Issue by fent** [giltesa/Game-Boy-Advance-SP-USB-C-charging-kit#4]
Hi, thank you for this usb-c mod

my soldering and de-soldering skills aren't great, so i've broken off the metal pads that connect to the pins of the usb-c connector. there is only 1 left:

![IMG_4875](https://github.com/giltesa/Game-Boy-Advance-SP-USB-C-charging-kit/assets/933490/af11f9d3-5737-445d-9216-095abe915e4d)

in the installation guide, there is a page on alternate pins:
![image](https://github.com/giltesa/Game-Boy-Advance-SP-USB-C-charging-kit/assets/933490/bf67ca71-8209-4fe3-9c0e-94db443e77b0)

but it seems to be for the other side of the pcb. are there such pins on the side where the usb-c connector is placed?

**Comment by giltesa** [comment]
Hello,

Certainly, those pads will also be connected to the CPU; however, it will be impossible for you to solder the wires there. You must use the recommended pads, use very thin wire, and you won't have any problems running the wires from one side to the other side of the PCB.

Kind regards,
giltesa

**Comment by fent** [comment]
Update: it worked! thanks!
